version: '3.8'

services:
  satori:
    image: satorinet/satorineuron:p2p
    container_name: satorip2p # Name of the container
    restart: unless-stopped
    network_mode: "host" # Use host network mode for direct access to ports
    volumes:
      # For Windows, use absolute paths with drive letter
      - C:\Users\satori-p2p\windows\config:/Satori/Neuron/config
      - C:\Users\satori-p2p\windows\wallet:/Satori/Neuron/wallet
      - C:\Users\satori-p2p\windows\data:/Satori/Neuron/data
      - C:\Users\satori-p2p\windows\models:/Satori/Neuron/models
    environment:
      - ENV=prod
    deploy:
      resources: # change this accordingly if needed 
        limits:
          cpus: "1.3"
          memory: "3.5g"
    stdin_open: true
    tty: true
    pull_policy: always
    entrypoint: ["bash", "/Satori/Neuron/satorineuron/web/start.sh"]